In [4]:
import numpy as np

In [5]:
fibb=np.zeros(10,dtype='int64')

In [6]:
fibb

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [7]:
fibb[1]

0

In [8]:
fibb[0]=0
fibb[1]=1

In [9]:
fibb

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [10]:
for i in range(2,fibb.size):
    fibb[i]=fibb[i-2]+fibb[i-1]
    
    

In [11]:
fibb

array([ 0,  1,  1,  2,  3,  5,  8, 13, 21, 34], dtype=int64)

In [12]:
fibb=fibb.reshape(2,5)

In [13]:
fibb

array([[ 0,  1,  1,  2,  3],
       [ 5,  8, 13, 21, 34]], dtype=int64)

In [14]:
arr=np.array([[[1,2,3,4],[5,6,7,8]],[[8,7,6,5],[4,3,2,1]]])

In [15]:
arr

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[8, 7, 6, 5],
        [4, 3, 2, 1]]])

In [16]:
arr.ndim

3

In [17]:
arr1=np.random.randint(low=12,high=45,size=(5,2,2))

In [18]:
arr1

array([[[30, 44],
        [38, 19]],

       [[25, 22],
        [18, 37]],

       [[23, 18],
        [40, 29]],

       [[41, 19],
        [22, 44]],

       [[27, 15],
        [36, 23]]])

In [19]:
arr1.shape

(5, 2, 2)

In [20]:
arr1.ndim

3

In [23]:
r=np.random.randint(10,20,(6,6))

In [24]:
r

array([[15, 15, 18, 16, 13, 13],
       [14, 19, 17, 14, 10, 12],
       [16, 16, 12, 17, 19, 10],
       [16, 18, 17, 14, 15, 15],
       [13, 17, 13, 15, 16, 19],
       [19, 13, 17, 19, 13, 16]])

In [25]:
r.reshape(2,18)

array([[15, 15, 18, 16, 13, 13, 14, 19, 17, 14, 10, 12, 16, 16, 12, 17,
        19, 10],
       [16, 18, 17, 14, 15, 15, 13, 17, 13, 15, 16, 19, 19, 13, 17, 19,
        13, 16]])

In [26]:
arr=np.random.randint(1,10,(3,3))

In [27]:
arr

array([[1, 3, 8],
       [9, 7, 9],
       [2, 9, 3]])

In [28]:
arr.sum(axis=0)

array([12, 19, 20])

In [29]:
arr.sum(axis=1)

array([12, 25, 14])

In [30]:
arr.argsort(axis=0)

array([[0, 0, 2],
       [2, 1, 0],
       [1, 2, 1]], dtype=int64)

In [33]:
y=np.eye(4,5)

In [34]:
y

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [35]:
arr2=np.random.randint(1,20,(7,6))

In [36]:
arr2

array([[ 4,  7,  4,  1, 17,  7],
       [13, 19, 10, 19,  3,  5],
       [ 8, 14,  1,  7,  3, 12],
       [13, 10, 11,  5,  7,  1],
       [12, 16, 14, 17, 10,  1],
       [ 3,  7,  7,  2, 17,  6],
       [ 3, 17,  6,  7, 17,  5]])

In [37]:
arr2.T

array([[ 4, 13,  8, 13, 12,  3,  3],
       [ 7, 19, 14, 10, 16,  7, 17],
       [ 4, 10,  1, 11, 14,  7,  6],
       [ 1, 19,  7,  5, 17,  2,  7],
       [17,  3,  3,  7, 10, 17, 17],
       [ 7,  5, 12,  1,  1,  6,  5]])

In [47]:
arr3=np.zeros([7,6],dtype='float64')

In [48]:
arr3

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [49]:
arr2

array([[ 4,  7,  4,  1, 17,  7],
       [13, 19, 10, 19,  3,  5],
       [ 8, 14,  1,  7,  3, 12],
       [13, 10, 11,  5,  7,  1],
       [12, 16, 14, 17, 10,  1],
       [ 3,  7,  7,  2, 17,  6],
       [ 3, 17,  6,  7, 17,  5]])

In [52]:
for i in range(0,7):
    for j in range(0,6):
        arr3[i,j]=arr2[i,j]*arr2[i,j]*np.pi

In [53]:
arr3

array([[  50.26548246,  153.93804003,   50.26548246,    3.14159265,
         907.92027689,  153.93804003],
       [ 530.92915846, 1134.11494795,  314.15926536, 1134.11494795,
          28.27433388,   78.53981634],
       [ 201.06192983,  615.7521601 ,    3.14159265,  153.93804003,
          28.27433388,  452.38934212],
       [ 530.92915846,  314.15926536,  380.13271108,   78.53981634,
         153.93804003,    3.14159265],
       [ 452.38934212,  804.24771932,  615.7521601 ,  907.92027689,
         314.15926536,    3.14159265],
       [  28.27433388,  153.93804003,  153.93804003,   12.56637061,
         907.92027689,  113.09733553],
       [  28.27433388,  907.92027689,  113.09733553,  153.93804003,
         907.92027689,   78.53981634]])

In [56]:
arr2

array([[ 4,  7,  4,  1, 17,  7],
       [13, 19, 10, 19,  3,  5],
       [ 8, 14,  1,  7,  3, 12],
       [13, 10, 11,  5,  7,  1],
       [12, 16, 14, 17, 10,  1],
       [ 3,  7,  7,  2, 17,  6],
       [ 3, 17,  6,  7, 17,  5]])

In [57]:
arr2[0,1]

7

In [59]:
arr[1,2]

9

In [60]:
arr2

array([[ 4,  7,  4,  1, 17,  7],
       [13, 19, 10, 19,  3,  5],
       [ 8, 14,  1,  7,  3, 12],
       [13, 10, 11,  5,  7,  1],
       [12, 16, 14, 17, 10,  1],
       [ 3,  7,  7,  2, 17,  6],
       [ 3, 17,  6,  7, 17,  5]])

In [67]:
arr2[:,[1,2,4]]

array([[ 7,  4, 17],
       [19, 10,  3],
       [14,  1,  3],
       [10, 11,  7],
       [16, 14, 10],
       [ 7,  7, 17],
       [17,  6, 17]])

In [68]:
arr2[:,:]

array([[ 4,  7,  4,  1, 17,  7],
       [13, 19, 10, 19,  3,  5],
       [ 8, 14,  1,  7,  3, 12],
       [13, 10, 11,  5,  7,  1],
       [12, 16, 14, 17, 10,  1],
       [ 3,  7,  7,  2, 17,  6],
       [ 3, 17,  6,  7, 17,  5]])

In [71]:
arr2[4:,3:]

array([[17, 10,  1],
       [ 2, 17,  6],
       [ 7, 17,  5]])

In [72]:
arr2[0,0:]

array([ 4,  7,  4,  1, 17,  7])

In [74]:
arr2

array([[ 4,  7,  4,  1, 17,  7],
       [13, 19, 10, 19,  3,  5],
       [ 8, 14,  1,  7,  3, 12],
       [13, 10, 11,  5,  7,  1],
       [12, 16, 14, 17, 10,  1],
       [ 3,  7,  7,  2, 17,  6],
       [ 3, 17,  6,  7, 17,  5]])

In [73]:
arr2[2,1:]

array([14,  1,  7,  3, 12])

In [75]:
arr2[[1,2,3],0]

array([13,  8, 13])

In [76]:
arr2

array([[ 4,  7,  4,  1, 17,  7],
       [13, 19, 10, 19,  3,  5],
       [ 8, 14,  1,  7,  3, 12],
       [13, 10, 11,  5,  7,  1],
       [12, 16, 14, 17, 10,  1],
       [ 3,  7,  7,  2, 17,  6],
       [ 3, 17,  6,  7, 17,  5]])

In [77]:
arr2[1:4,0]

array([13,  8, 13])

In [78]:
arr2

array([[ 4,  7,  4,  1, 17,  7],
       [13, 19, 10, 19,  3,  5],
       [ 8, 14,  1,  7,  3, 12],
       [13, 10, 11,  5,  7,  1],
       [12, 16, 14, 17, 10,  1],
       [ 3,  7,  7,  2, 17,  6],
       [ 3, 17,  6,  7, 17,  5]])

In [80]:
arr2[:,1:4]

array([[ 7,  4,  1],
       [19, 10, 19],
       [14,  1,  7],
       [10, 11,  5],
       [16, 14, 17],
       [ 7,  7,  2],
       [17,  6,  7]])

In [81]:
arr2[-3:,0:]

array([[12, 16, 14, 17, 10,  1],
       [ 3,  7,  7,  2, 17,  6],
       [ 3, 17,  6,  7, 17,  5]])

In [82]:
arr2

array([[ 4,  7,  4,  1, 17,  7],
       [13, 19, 10, 19,  3,  5],
       [ 8, 14,  1,  7,  3, 12],
       [13, 10, 11,  5,  7,  1],
       [12, 16, 14, 17, 10,  1],
       [ 3,  7,  7,  2, 17,  6],
       [ 3, 17,  6,  7, 17,  5]])

In [83]:
j=arr2>5# it will perform the condition on all the arr elements

In [84]:
j

array([[False,  True, False, False,  True,  True],
       [ True,  True,  True,  True, False, False],
       [ True,  True, False,  True, False,  True],
       [ True,  True,  True, False,  True, False],
       [ True,  True,  True,  True,  True, False],
       [False,  True,  True, False,  True,  True],
       [False,  True,  True,  True,  True, False]])

In [85]:
arr2

array([[ 4,  7,  4,  1, 17,  7],
       [13, 19, 10, 19,  3,  5],
       [ 8, 14,  1,  7,  3, 12],
       [13, 10, 11,  5,  7,  1],
       [12, 16, 14, 17, 10,  1],
       [ 3,  7,  7,  2, 17,  6],
       [ 3, 17,  6,  7, 17,  5]])

In [88]:
arr=np.full((4,3,2),20)

In [89]:
arr

array([[[20, 20],
        [20, 20],
        [20, 20]],

       [[20, 20],
        [20, 20],
        [20, 20]],

       [[20, 20],
        [20, 20],
        [20, 20]],

       [[20, 20],
        [20, 20],
        [20, 20]]])

In [93]:
arr4=np.full((4,4),[9,7,5,9])

In [94]:
arr4

array([[9, 7, 5, 9],
       [9, 7, 5, 9],
       [9, 7, 5, 9],
       [9, 7, 5, 9]])