# numpy
1. faster than list
2.compact
3.less memory

In [2]:
import numpy as np

In [3]:
k=np.array([1,2,3,4])

In [4]:
k.dtype

dtype('int32')

In [5]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [6]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
type(a)

numpy.ndarray

In [8]:
a.dtype

dtype('int32')

In [9]:
a.shape

(3, 3)

In [10]:
a.size

9

In [11]:
a.itemsize

4

In [12]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
a[2,2]=0

In [14]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]])

In [15]:
ls=np.array([1,2,3,4], dtype='int64')

In [16]:
ls.dtype

dtype('int64')

In [17]:
zeros=np.zeros([5,3])

In [18]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
ones=np.ones([2,2])

In [20]:
ones

array([[1., 1.],
       [1., 1.]])

In [21]:
ones.ndim

2

In [22]:
n=np.array([[1,2,3,4],[5,6,7,8]])

In [23]:
n.itemsize# memory occupied  by the array

4

In [24]:
n

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [25]:
n.ndim

2

In [26]:
n.shape

(2, 4)

In [27]:
ra=np.arange(1,5)

In [28]:
ra

array([1, 2, 3, 4])

In [29]:
ra=ra.reshape(2,2)

In [30]:
ra

array([[1, 2],
       [3, 4]])

In [31]:
ra.ravel()

array([1, 2, 3, 4])

In [32]:
arr2=np.arange(1,7).reshape(2,3)

In [33]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
j=[1,2,3,5]
j=[i+3 for i in j]# list  comprehensive
print(j)

[4, 5, 6, 8]


In [35]:
s=np.array([1,2,3,5])
s=s+3

In [36]:
s

array([4, 5, 6, 8])

In [37]:
x=np.ones([3,4],dtype='int64')

In [38]:
x

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int64)

In [39]:
y=np.zeros(shape=(2,3))

In [40]:
y

array([[0., 0., 0.],
       [0., 0., 0.]])

In [41]:
x.dtype# 

dtype('int64')

In [42]:
h1=np.arange(0,11,2).reshape(2,3)

In [43]:
h1

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [44]:
one=np.ones_like(h1)

In [45]:
one

array([[1, 1, 1],
       [1, 1, 1]])

In [46]:
zero=np.zeros_like(h1)

In [47]:
zero

array([[0, 0, 0],
       [0, 0, 0]])

In [48]:
lspace=np.linspace(1,10,5)

In [49]:
lspace

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [50]:
emp=np.empty([2,2])

In [51]:
emp

array([[1., 1.],
       [1., 1.]])

In [52]:
ide=np.identity(4)

In [53]:
ide

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [54]:
j1=np.arange(10,1,-3)

In [55]:
j1

array([10,  7,  4])

In [56]:
a=np.linspace(1,10,20,retstep=True)

In [57]:
a

(array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
         3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
         5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
         8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ]),
 0.47368421052631576)

In [58]:
a[0][1]-a[0][2]

-0.4736842105263157

In [60]:
type(a)

tuple

In [63]:
b=np.random.rand(5,3)

In [65]:
b.dtype

dtype('float64')

In [ ]:
b

array([[0.42478874, 0.98009229, 0.66592586],
       [0.70130053, 0.67497181, 0.42514825],
       [0.36621066, 0.60046529, 0.75534409],
       [0.90097977, 0.03173103, 0.21219349],
       [0.38768725, 0.28159069, 0.02332089]])